
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 20
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.name }}
              topologyKey: failure-domain.kubernetes.io/zone
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.registry }}/{{ .Values.name }}:{{ .Values.tag }}"
          envFrom:
          - configMapRef:
              name: {{ .Values.configmap }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: {{ .Values.health_check_path }}
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: {{ .Values.health_check_path }}
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            limits:
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 70Mi
          securityContext:
            privileged: true
---