name: CI/CD API

on:
  push:
    branches:
      - 'main'

env:
  APP_NAME: ruby_api
  SRC_PATH: api
  REGISTRY: anilerencelik

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          cd $SRC_PATH
          docker build -t ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}  .

      - name: Run DB initilazer
        run: |
          docker run --rm -e REDIS_URL=${{ secrets.REDIS_URL }} -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} -e PIDFILE=${{ secrets.PIDFILE }} ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }} bundle exec rails db:create

      - name: Run DB migrator
        run: |
          docker run --rm -e REDIS_URL=${{ secrets.REDIS_URL }} -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} -e PIDFILE=${{ secrets.PIDFILE }} ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }} bundle exec rails db:migrate db:seed

      - name: Runing rake test
        run: |
          docker run --rm -e REDIS_URL=${{ secrets.REDIS_URL }} -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} -e PIDFILE=${{ secrets.PIDFILE }} ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }} bundle exec rake test
        
      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}
        env:
          DOCKER_CLI_ABOVE_VERSION: 1.22.0